version: '3'

services:
  app:
    image: rodrigopacheco100/node-nginx
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh npm start
    tty: true
    networks:
      - app-tier
    volumes:
      - "./:/app"
    depends_on:
      db:
        condition: service_started

  db:
    image: 'bitnami/mysql:latest'
    networks:
      - app-tier
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
